import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import BreakpointIndicator from "@/components/dev/breakpoint-indicator";
import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import "@/styles/globals.css";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <div data-vaul-drawer-wrapper className="bg-background">
          <Navbar />
          {children}
          <Footer />
          <BreakpointIndicator />
        </div>
      </body>
    </html>
  );
}
